"""Host-side registry of live lmer sessions the platform owns.

Why this exists
---------------
The platform's inventory is keyed on *runs*, not sessions (spec D15), and run
state comes from the work repo. But the work repo knows nothing about the host
facts that make a session reachable and controllable — its PID, its container id,
the port its control plane bound, the port mappings it published, where its
transcript and PTY log live. Those facts have no home anywhere else, so each live
session gets a file here and the daemon aggregates them (spec §6.1).

One file per session, not one shared index
------------------------------------------
This is the same shape as :mod:`slack_chat.registry`, for the same reason: a
single shared index would need every writer to read-modify-write it, and that
race is what its module docstring spends sixty lines explaining. One file per
session means one writer per file, so an atomic replace is the whole concurrency
story.

Where this deliberately diverges from the Slack registry
--------------------------------------------------------
Two differences, both forced by the platform's topology rather than by taste:

- **Two PIDs, not one.** In the Slack module the process that registers *is* the
  session, so ``pid`` serves as both the liveness signal and the ownership
  token. Here the daemon spawns sessions as children and writes entries
  describing them, so those roles split: ``pid`` is the session's own process
  (the liveness signal, and it must be the child's — sessions outlive the daemon,
  spec R11), while ``owner_pid`` is the writer. Delete is checked against
  ``owner_pid`` so a second, misconfigured daemon cannot remove entries it does
  not own.
- **Stale entries need an explicit sweep.** The Slack registry is keyed on the
  thread, so a thread's next ``register`` atomically overwrites whatever stale
  entry was there and litter cannot accumulate. Session ids are unique per
  session, so nothing ever overwrites a dead session's entry. :func:`prune_dead`
  is therefore the reclaim path — a deliberate write by the single writer, not a
  mutation smuggled into a read. Reads still never mutate: the race that opens
  (unlinking *by path* what a concurrent register may have just rewritten) is
  real regardless of what the key is.

Reads are tolerant by contract. One unreadable entry must not take out the whole
fleet view, so a corrupt file is logged and skipped rather than raised — the
opposite trade from :func:`lmer_platform.store.write_json`, where losing a write
is the unrecoverable direction.
"""

from __future__ import annotations

import logging
import os
import re
import uuid
from pathlib import Path
from typing import Optional

from . import SCHEMA_VERSION
from .store import (
    StoreError, mutating, read_json, sessions_dir, utc_now_iso, write_json,
)

logger = logging.getLogger("lmer_platform.registry")

__all__ = [
    "RegistryError", "SESSION_KINDS", "WORKER_KIND", "ASSISTANT_KIND",
    "new_session_id", "session_path",
    "token_path", "register", "update", "read_session", "list_sessions",
    "remove", "prune_dead", "is_live",
]

#: A session is either a worker doing a task or the orchestrating assistant.
#:
#: Named individually because the *values* are read outside this module and the
#: reader cannot always be the module that owns the thing being named:
#: :func:`lmer_platform.spawn._live_worker_count` has to tell the assistant's
#: entry from a worker's to hold the concurrency cap over workers only, and
#: :mod:`lmer_platform.spawn` cannot import :mod:`lmer_platform.assistant` — the
#: dependency runs the other way, since the assistant is spawned through it. The
#: registry is where both of them already look for what a ``kind`` may be, so it
#: is where the one definition of each value goes; ``assistant.KIND`` is an alias
#: of this rather than a second string.
WORKER_KIND = "worker"
ASSISTANT_KIND = "assistant"
SESSION_KINDS = (WORKER_KIND, ASSISTANT_KIND)

#: Session ids are generated by :func:`new_session_id` and land in a filename,
#: so the character set is restricted. Ids are validated rather than sanitized:
#: silently mangling one could map two distinct sessions onto a single file.
_SESSION_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


class RegistryError(RuntimeError):
    """Raised on a malformed registration — a caller bug, not a runtime state."""


def new_session_id() -> str:
    """A fresh session id: sortable timestamp plus a short random suffix.

    The timestamp makes a directory listing chronological, which matters when
    reading these files by hand during a post-mortem; the suffix keeps two
    sessions started in the same second distinct.
    """
    stamp = utc_now_iso().replace("-", "").replace(":", "").replace("Z", "")
    return f"s-{stamp}-{uuid.uuid4().hex[:4]}"


def _validate_session_id(session_id: str) -> str:
    if not isinstance(session_id, str) or not _SESSION_ID_RE.match(session_id or ""):
        raise RegistryError(
            f"invalid session id {session_id!r}: expected "
            "alphanumerics, dot, dash or underscore"
        )
    if os.sep in session_id or "/" in session_id:  # pragma: no cover - regex covers
        raise RegistryError(f"invalid session id {session_id!r}: path separator")
    return session_id


def session_path(session_id: str) -> Path:
    """Path of one session's registry file."""
    return sessions_dir() / f"{_validate_session_id(session_id)}.json"


def token_path(session_id: str) -> Path:
    """Path of the sibling file holding one session's control-plane token.

    This module owns ``sessions/``, so it owns the *name*; only
    :mod:`lmer_platform.spawn` ever writes or reads the contents. Naming it here
    is what lets :func:`remove` clean the token up with the entry instead of
    leaving credentials behind for every session that was ever pruned.

    Derived from the session id, deliberately **not** read from the entry's
    ``control.token_ref``: that value is caller-supplied data, and unlinking
    whatever path it happens to contain would turn a hand-edited registry file
    into an arbitrary-file delete.
    """
    return session_path(session_id).with_suffix(".token")


def _is_zombie(pid: int) -> bool:
    """Whether *pid* is an exited-but-unreaped zombie, where that is knowable.

    This matters because the daemon is the **parent** of every session it spawns,
    so a child that has exited but not yet been reaped still answers
    ``kill(pid, 0)`` and would read as alive. Not theoretical: a ``kill -9``'d
    session reported as ``running`` until this check existed.

    Reads ``/proc/<pid>/stat``. The ``comm`` field is parenthesised and may itself
    contain spaces, so the state code is taken from the text after the final
    ``)``. Where ``/proc`` is absent — macOS — the answer is "not a zombie", which
    degrades to the previous behavior; the waiter thread in
    :mod:`lmer_platform.spawn` reaps promptly there, keeping the window small.
    """
    try:
        with open(f"/proc/{pid}/stat", "r", encoding="utf-8") as handle:
            stat_line = handle.read()
    except OSError:
        return False
    _, _, rest = stat_line.rpartition(")")
    fields = rest.split()
    return bool(fields) and fields[0] == "Z"


def _pid_alive(pid: object) -> bool:
    """Whether *pid* names a live process.

    POSIX ``kill(pid, 0)`` existence probe, plus a zombie check: a process that has
    exited without being reaped still "exists" as far as ``kill`` is concerned, and
    counting that as alive keeps dead sessions in the fleet view.

    ``PermissionError`` means the process exists but belongs to another user, which
    counts as alive — the platform would rather show a session it cannot signal
    than silently drop a running one from the inventory.
    """
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return not _is_zombie(pid)


def is_live(entry: Optional[dict]) -> bool:
    """Whether a registry entry describes a process that still exists."""
    if not isinstance(entry, dict):
        return False
    return _pid_alive(entry.get("pid"))


def _reject_inline_token(control: Optional[dict]) -> None:
    """Refuse a raw bearer token in ``control``.

    Registry files are debugging artifacts people ``cat`` and paste into
    tickets; a token that grants full control of a session must not be in one
    (spec §6.2). The entry carries a ``token_ref`` pointing at a mode-0600 file
    instead. Enforced here rather than documented, because a convention that
    only lives in prose gets broken by the first caller in a hurry.
    """
    if isinstance(control, dict) and "token" in control:
        raise RegistryError(
            "control must carry 'token_ref' (a path), never an inline 'token'"
        )


def register(
    session_id: str,
    *,
    kind: str = "worker",
    pid: int,
    task: Optional[dict] = None,
    run: Optional[dict] = None,
    control: Optional[dict] = None,
    ports: Optional[list] = None,
    transcript: Optional[dict] = None,
    container_id: Optional[str] = None,
    slot: Optional[str] = None,
    slack: Optional[dict] = None,
    started_at: Optional[str] = None,
    log_path: Optional[str] = None,
) -> dict:
    """Record a live session and return the entry as written.

    ``pid`` is the *session's* process — the host-side ``lmer`` whose lifetime is
    the session's — not the caller's. Liveness is read from it, so recording the
    daemon's own PID here would make every session look alive for as long as the
    daemon runs.

    Unlike the Slack registry this is not best-effort: an entry that fails to
    land means a session nobody can find or control, which is worse than a failed
    spawn. :class:`~lmer_platform.store.StoreError` propagates.
    """
    if kind not in SESSION_KINDS:
        raise RegistryError(
            f"invalid session kind {kind!r}: expected one of {', '.join(SESSION_KINDS)}"
        )
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        raise RegistryError(f"invalid pid {pid!r}: expected a positive integer")
    _reject_inline_token(control)

    entry = {
        "schema": SCHEMA_VERSION,
        "id": _validate_session_id(session_id),
        "kind": kind,
        "pid": pid,
        "owner_pid": os.getpid(),
        "started_at": started_at or utc_now_iso(),
        "container_id": container_id,
        "task": task or {},
        "run": run or {},
        "control": control or {},
        "ports": ports or [],
        "transcript": transcript or {},
        "log_path": log_path,
        "slot": slot,
        "slack": slack or {},
    }
    write_json(session_path(session_id), entry)
    logger.debug(
        "platform_session_registered id=%s kind=%s pid=%s", session_id, kind, pid
    )
    return entry


def update(session_id: str, **fields) -> Optional[dict]:
    """Merge *fields* into an existing entry and rewrite it atomically.

    Exists because facts arrive after the spawn: a container id, the port
    mappings the runtime actually published, a transcript path that only appears
    once the harness starts. Returns the updated entry, or ``None`` when there is
    nothing to update (the session already exited and was reaped).

    Only the writer that registered the session should call this — the daemon.
    ``owner_pid`` is refreshed so ownership follows the current writer after a
    daemon restart that re-adopted the session.
    """
    _reject_inline_token(fields.get("control"))
    path = session_path(session_id)
    # Read-modify-write, so it is held under the entry's lock: two facts arriving
    # at once (the container id from the spawn thread, the published ports the
    # session reports about itself) would otherwise each write the whole entry
    # from its own read, and the loser's field would simply not be there.
    with mutating(path):
        entry = read_session(session_id)
        if entry is None:
            logger.debug("platform_session_update_skipped id=%s (absent)", session_id)
            return None
        entry.update(fields)
        entry["owner_pid"] = os.getpid()
        write_json(path, entry)
    return entry


def read_session(session_id: str) -> Optional[dict]:
    """One entry, or ``None`` when absent or unreadable.

    Tolerant on purpose: a corrupt entry is logged and skipped so one bad file
    cannot take out the whole inventory. ``store.read_json`` has already moved
    the bad bytes aside for post-mortem.
    """
    try:
        return read_json(session_path(session_id))
    except StoreError as exc:
        logger.warning(
            "platform_session_unreadable id=%s error=%s", session_id, exc
        )
        return None


def list_sessions(*, live_only: bool = True) -> list[dict]:
    """Every registered session, oldest first, each carrying a computed ``live``.

    ``live`` is derived on read and never persisted. With ``live_only`` (the
    default) stale entries are filtered out but left on disk — reclaiming them is
    :func:`prune_dead`'s job, so that reads stay side-effect free.
    """
    directory = sessions_dir()
    try:
        paths = sorted(directory.glob("*.json"))
    except OSError as exc:
        logger.warning("platform_session_list_failed dir=%s error=%s", directory, exc)
        return []

    entries: list[dict] = []
    for path in paths:
        try:
            entry = read_json(path)
        except StoreError as exc:
            logger.warning("platform_session_unreadable path=%s error=%s", path, exc)
            continue
        if entry is None:
            continue
        entry["live"] = is_live(entry)
        if live_only and not entry["live"]:
            continue
        entries.append(entry)
    entries.sort(key=lambda e: (e.get("started_at") or "", e.get("id") or ""))
    return entries


def remove(session_id: str, *, force: bool = False) -> bool:
    """Delete an entry this process owns. Returns whether a file was removed.

    Ownership is checked against ``owner_pid`` so two daemons cannot delete each
    other's entries — but only while that owner is still alive, so a crashed
    daemon's entries can be reclaimed by its successor. An ownerless entry is
    removed regardless: it protects nothing.

    A *corrupt* entry never reaches the ownership check, because
    :func:`~lmer_platform.store.read_json` relocates unparseable bytes to
    ``.bad-<stamp>`` before raising. Such an entry has therefore already left the
    registry by the time this is called, and the return value is ``False`` —
    truthfully, since nothing was unlinked here.

    ``force`` skips the ownership check entirely; :func:`prune_dead` uses it.

    The session's control token (:func:`token_path`) goes with the entry, and
    only when the entry actually went: a removal this process declined, or an
    entry already moved aside as corrupt, leaves the token alone. Without this,
    every pruned session would leave a live credential in ``sessions/`` with
    nothing left pointing at it — the entry that documented what it was for is
    exactly what just got deleted.
    """
    path = session_path(session_id)
    entry = read_session(session_id)
    if entry is not None and not force:
        owner = entry.get("owner_pid")
        if isinstance(owner, int) and owner != os.getpid() and _pid_alive(owner):
            logger.debug(
                "platform_session_remove_skipped id=%s owner_pid=%s (not ours)",
                session_id, owner,
            )
            return False
    try:
        path.unlink()
    except FileNotFoundError:
        return False
    except OSError as exc:
        logger.warning(
            "platform_session_remove_failed id=%s error=%s", session_id, exc
        )
        return False
    try:
        token_path(session_id).unlink()
    except FileNotFoundError:
        pass
    except OSError as exc:
        # Not fatal: the entry is gone, which is what the caller asked for. Loud
        # enough to notice, because what is left behind is a credential.
        logger.warning(
            "platform_session_token_remove_failed id=%s error=%s", session_id, exc
        )
    logger.debug("platform_session_deregistered id=%s", session_id)
    return True


def prune_dead() -> list[str]:
    """Remove entries whose session process is gone. Returns the ids removed.

    The explicit reclaim path (see the module docstring): unique session ids mean
    nothing ever overwrites a dead session's entry, so without this the directory
    accumulates litter forever.

    Called only from the deliberate ``prune`` action — never from a read, and
    never as a side effect of refreshing the fleet view. A stale entry is the
    evidence that a session crashed (:mod:`lmer_platform.inventory` reads it as
    exactly that), so discarding it is an acknowledgement the operator makes, not
    housekeeping that quietly erases a crash nobody saw.

    ``force=True`` because the sessions being pruned are dead by definition, and
    their entries are frequently owned by a *previous* daemon process; refusing
    to clean those up is exactly the litter this exists to remove.
    """
    removed: list[str] = []
    for entry in list_sessions(live_only=False):
        if entry.get("live"):
            continue
        session_id = entry.get("id")
        if not isinstance(session_id, str):
            continue
        if remove(session_id, force=True):
            removed.append(session_id)
    if removed:
        logger.info("platform_sessions_pruned count=%d", len(removed))
    return removed
