"""Push allow-list grammar parity across the standalone mirrors (#116).

LMER_PUSH_ALLOW_LIST is enforced at three points:

- src/lmer_cli/gates.py run_push_gate — the source of truth;
- hooks/pc.py push_allowed — stdlib-only in-container hook that cannot
  import lmer_cli (same standalone constraint as container/clone_and_exec.py,
  cf. lmer_cli/tokens.py);
- the POSIX-sh pre-push hook generated by the heredoc in hooks/install.sh.

The latter two DUPLICATE the extended grammar (`repo` for branch refs only,
`repo|refpattern` for fnmatch against the fully-qualified ref; malformed
entries ignored fail-closed). Per the mirrored-logic convention
(tests/test_harness_runners.py, tests/test_masterplan_provisioning.py), a
duplicated implementation is acceptable only with a guard test — this module
is that guard and the resolution mechanism for issue #116: every live
implementation must return the same allow/deny verdict over the shared case
table below, so the ref-scoped rule cannot be bypassed by whichever
enforcement point an agent happens to hit.

Two rules sit alongside the entry grammar and are guarded here too:

- **Ref deletion is never authorized** — gates.py refuses an empty-`<src>`
  refspec, the pre-push hook refuses git's deletion line. Neither can be
  granted by an allow-list entry.
- **Push-by-URL matches ANCHORED** — when git was handed a URL instead of a
  configured remote, the repo half must name the URL's `host/path` or its
  `host`, not merely appear inside it. hooks/pc.py has no
  push-by-URL path (its URL is always `git remote get-url --push origin`) and no
  deletion path (its ref is always `git branch --show-current`), so those
  two rules are parity-checked across gates.py and the generated hook only.

**A parity suite that only cross-compares the mirrors is blind to a bug they
SHARE** — which is exactly how the last-`@` userinfo strip survived: all three
copies normalized `https://evil.example.com/x@github.com/group/project` to
`github.com/group/project`, so they agreed, and agreement was the whole test.
Two guards close that hole: `URL_IDENTITIES` states the expected `host/path`
for each URL as a hand-written constant (derived from what `urlsplit` and git
itself say, not from any implementation), and
`test_the_authorized_host_is_the_host_git_would_dial` asserts the PROPERTY a
shared bug violates — no implementation may authorize an entry naming a host
other than the one git dials.
"""
import importlib.util
import os
import re
import subprocess
from pathlib import Path
from urllib.parse import urlsplit

import pytest

from lmer_cli.gates import GateSystem

REPO_ROOT = Path(__file__).parent.parent
PC_HOOK_PATH = REPO_ROOT / "hooks" / "pc.py"
INSTALL_SH_PATH = REPO_ROOT / "hooks" / "install.sh"

GITLAB_SSH = "git@gitlab.example.com:group/project.git"
GITHUB_MIRROR = "https://github.com/group/project.git"

# Plausible object names for the pre-push stdin protocol
# ("<local_ref> <local_sha> <remote_ref> <remote_sha>").
LOCAL_SHA = "1" * 40
REMOTE_SHA = "2" * 40
ZERO_SHA = "0" * 40

# Shared verdict table: (allow-list entry/entries, remote URL, ref, expected).
# Refs are fully qualified — that is what git hands the pre-push hook on
# stdin (bare-branch normalization is a python-side nicety, tested apart).
CASES = [
    # Bare entry (no `|`): branch refs ONLY. The repo half is matched by
    # the #107 grammar — here the legacy host-less project path rule.
    ("group/project", GITLAB_SSH, "refs/heads/main", True),
    ("group/project", GITLAB_SSH, "refs/tags/v0.2.0", False),  # bare vs tag ref
    # Explicit refs/tags/* entry grants tags, and only tags.
    ("group/project|refs/tags/*", GITLAB_SSH, "refs/tags/v0.2.0", True),
    ("group/project|refs/tags/*", GITLAB_SSH, "refs/heads/main", False),
    # GitHub mirror remote: entry names the mirror repo, scoped by URL.
    ("github.com/group/project|refs/heads/main", GITHUB_MIRROR, "refs/heads/main", True),
    ("github.com/group/project|refs/heads/main", GITLAB_SSH, "refs/heads/main", False),
    ("github.com/group/project|refs/tags/*", GITHUB_MIRROR, "refs/tags/v0.2.0", True),
    # The release-flow grant shape: tags to origin + mirror branch push.
    ("group/project|refs/tags/*, github.com/group/project|refs/heads/main",
     GITLAB_SSH, "refs/tags/v0.2.0", True),
    ("group/project|refs/tags/*, github.com/group/project|refs/heads/main",
     GITHUB_MIRROR, "refs/heads/main", True),
    ("group/project|refs/tags/*, github.com/group/project|refs/heads/main",
     GITLAB_SSH, "refs/heads/feature-x", False),
    # Malformed entries (empty half, >1 delimiter) are ignored fail-closed.
    ("|refs/tags/*", GITLAB_SSH, "refs/tags/v0.2.0", False),
    ("group/project|", GITLAB_SSH, "refs/heads/main", False),
    ("a|b|c", GITLAB_SSH, "refs/heads/main", False),
    ("|refs/tags/*, group/project|, a|b|c", GITLAB_SSH, "refs/heads/main", False),
    # ... but a malformed neighbor does not poison a valid entry.
    ("a|b|c, group/project", GITLAB_SSH, "refs/heads/feature-x", True),
    # Empty / whitespace / non-matching lists deny.
    ("", GITLAB_SSH, "refs/heads/main", False),
    ("   ", GITLAB_SSH, "refs/heads/main", False),
    ("user/other-repo", GITLAB_SSH, "refs/heads/main", False),
    # Whitespace around entries and around the delimiter is trimmed.
    (" group/project | refs/tags/* ", GITLAB_SSH, "refs/tags/v0.2.0", True),

    # ---- #107 repo-half grammar; every point must agree on ALL of it ----
    # Exact repo: SSH / HTTPS / bare spellings are interchangeable.
    ("gitlab.example.com/group/project", GITLAB_SSH, "refs/heads/main", True),
    ("https://gitlab.example.com/group/project", GITLAB_SSH, "refs/heads/main", True),
    ("git@gitlab.example.com:group/project.git", GITLAB_SSH, "refs/heads/main", True),
    ("gitlab.example.com/group/other", GITLAB_SSH, "refs/heads/main", False),
    # Whole host: any project there, but the host must match exactly.
    ("gitlab.example.com", GITLAB_SSH, "refs/heads/main", True),
    ("sub.gitlab.example.com", GITLAB_SSH, "refs/heads/main", False),
    ("github.com", GITLAB_SSH, "refs/heads/main", False),
    # Wildcard domain: subdomains only, dot boundary enforced, apex excluded.
    ("*.example.com", GITLAB_SSH, "refs/heads/main", True),
    ("*.example.com", "git@example.com:group/project.git", "refs/heads/main", False),
    ("*.example.com", "git@evilexample.com:group/project.git", "refs/heads/main", False),
    ("*.example.com|refs/tags/*", GITLAB_SSH, "refs/tags/v0.2.0", True),
    ("*.example.com", GITLAB_SSH, "refs/tags/v0.2.0", False),  # bare: branches only
    # Host + project prefix, at SEGMENT boundaries.
    ("gitlab.example.com/group", GITLAB_SSH, "refs/heads/main", True),
    ("gitlab.example.com/group", "git@gitlab.example.com:groupfoo/x.git",
     "refs/heads/main", False),
    ("gitlab.example.com/gro", GITLAB_SSH, "refs/heads/main", False),
    # Legacy host-less path: any host, still segment-bounded.
    ("group/project", "https://other.example.org/group/project.git",
     "refs/heads/main", True),
    ("group/project", "https://gitlab.example.com/group/project2.git",
     "refs/heads/main", False),
    # The substring rule this grammar REPLACED would have allowed both of
    # these; every enforcement point must now refuse them.
    ("group/proj", GITLAB_SSH, "refs/heads/main", False),
    ("group/project", "https://evil.example.com/mirror/group/project.git",
     "refs/heads/main", False),
    # Hosts are case-insensitive; project paths are not.
    ("GITLAB.EXAMPLE.COM/group/project", GITLAB_SSH, "refs/heads/main", True),
    ("gitlab.example.com/Group/Project", GITLAB_SSH, "refs/heads/main", False),
    # Entry shapes that only exist once the two grammars are merged: a bare
    # entry and a ref-scoped entry, of different repo shapes, in one list.
    ("*.example.com, github.com/group/project|refs/tags/*",
     GITLAB_SSH, "refs/heads/main", True),
    ("*.example.com, github.com/group/project|refs/tags/*",
     GITHUB_MIRROR, "refs/tags/v0.2.0", True),
    ("*.example.com, github.com/group/project|refs/tags/*",
     GITHUB_MIRROR, "refs/heads/main", False),
    ("*.example.com, github.com/group/project|refs/tags/*",
     GITLAB_SSH, "refs/tags/v0.2.0", False),
    # A wildcard grant for one domain must not leak onto another host in
    # the same list, whichever half of the entry the ref matches.
    ("*.example.com|refs/tags/*, group/project",
     GITHUB_MIRROR, "refs/tags/v0.2.0", False),
    ("*.example.com|refs/tags/*, group/project",
     GITHUB_MIRROR, "refs/heads/main", True),

    # ---- Inputs no implementation may choke on or over-read ----
    # A malformed URL grants nothing AND does not abort the entries around
    # it: an unmatched IPv6 bracket raises inside urlsplit/urlparse, so an
    # unguarded parse would make the verdict depend on where the bad entry
    # sits in the list (it granted when listed second, crashed when first).
    ("https://[::1/g/p", GITLAB_SSH, "refs/heads/main", False),
    ("https://[::1/g/p, gitlab.example.com", GITLAB_SSH, "refs/heads/main", True),
    ("gitlab.example.com, https://[::1/g/p", GITLAB_SSH, "refs/heads/main", True),
    ("gitlab.example.com", "https://[::1/g/p", "refs/heads/main", False),
    # No scheme and no `:` before the first `/`: git reads the whole string
    # as a local PATH, so there is no authority and no userinfo to strip.
    # The `@` names no host (URL_IDENTITIES states None for this URL), so
    # nothing may authorize it — least of all the identity after the `@`.
    ("github.com", "user@github.com/group/project", "refs/heads/main", False),
    ("github.com/group/project", "user@github.com/group/project",
     "refs/heads/main", False),
    # An empty (or otherwise invalid) scheme is not a URL — git refuses it,
    # "protocol '' is not supported" — so the text after `://` is not a host.
    ("github.com", "://github.com/group/project", "refs/heads/main", False),
    ("github.com/group/project", "://github.com/group/project",
     "refs/heads/main", False),

    # ---- IPv6 literals: the BRACKET is the host boundary ----
    # The leak these rows exist for: splitting the authority on its first
    # `:` collapses every address sharing a first hextet to one host
    # (`[2001`), and every `::`-leading address to the host `[`, so an
    # entry naming one address authorized a push to a DIFFERENT one. The
    # mirrors did that while gate-push (urlsplit) resolved the real
    # address, which made them laxer than the gate.
    ("https://[2001:db8::1]/group/project",
     "https://[2001:db8::9999]/group/project", "refs/heads/main", False),
    ("https://[::1]/group/project", "https://[::2]/group/project",
     "refs/heads/main", False),
    ("https://[2001:db8::1]", "https://[2001:db8::9999]/group/project",
     "refs/heads/main", False),
    ("[2001:db8::1]", "git@[2001:db8::9999]:group/project.git",
     "refs/heads/main", False),
    # A truncated address is not a host prefix — `[2001` names nothing.
    ("[2001", "https://[2001:db8::1]/group/project", "refs/heads/main", False),
    ("[2001:db8::1", "https://[2001:db8::1]/group/project",
     "refs/heads/main", False),
    # ...and the exact address does grant, in every spelling git accepts:
    # they are one identity everywhere.
    ("https://[2001:db8::1]/group/project",
     "https://[2001:db8::1]/group/project", "refs/heads/main", True),
    ("[2001:db8::1]/group/project", "https://[2001:db8::1]/group/project",
     "refs/heads/main", True),
    ("[2001:db8::1]/group/project", "git@[2001:db8::1]:group/project.git",
     "refs/heads/main", True),
    ("[2001:db8::1]/group/project",
     "ssh://git@[2001:db8::1]:22/group/project.git", "refs/heads/main", True),
    ("https://[2001:db8::1]", "https://[2001:db8::1]/group/project",
     "refs/heads/main", True),
    ("[2001:db8::1]|refs/tags/*", "https://[2001:db8::1]/group/project",
     "refs/tags/v0.2.0", True),
    ("[2001:db8::1]", "https://[2001:db8::1]/group/project",
     "refs/tags/v0.2.0", False),          # bare entry: branches only
    # An unclosed bracket names no host, so nothing authorizes it — the
    # mirrors used to read it as host `[` with the path intact, which a
    # legacy host-less entry then granted.
    ("group/project", "https://[::1/group/project", "refs/heads/main", False),
    ("[::1]/group/project", "https://[::1/group/project",
     "refs/heads/main", False),
]


def _load_pc_hook():
    """Load hooks/pc.py by path — it is not an importable package module."""
    spec = importlib.util.spec_from_file_location("lmer_pc_hook", PC_HOOK_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _extract_pre_push_body():
    """Pull the generated pre-push hook out of install.sh's heredoc."""
    text = INSTALL_SH_PATH.read_text()
    marker = "cat > \"$GLOBAL_DIR/.git/hooks/pre-push\" << 'EOF'\n"
    start = text.index(marker) + len(marker)
    end = text.index("\nEOF\n", start)
    return text[start:end + 1]


PC_HOOK = _load_pc_hook()
PRE_PUSH_BODY = _extract_pre_push_body()


def gates_verdict(allow, url, ref, monkeypatch):
    """Allow/deny from the source of truth, gates.py run_push_gate.

    git calls are stubbed (remote get-url -> `url`) and the trailing
    commit-gate run is short-circuited so the return value IS the
    allow-list verdict.
    """
    monkeypatch.setenv("LMER_PUSH_ALLOW_LIST", allow)
    gate = GateSystem()

    def fake_run_command(command, check=True):
        # `--push` is mandatory: git pushes to remote.<name>.pushurl when it
        # is set, so gating the bare (fetch) url authorizes one repository
        # and pushes to another. Asserted for real against a configured
        # pushurl in test_gate_checks_the_pushurl_not_the_fetch_url.
        if command[:4] == ["git", "remote", "get-url", "--push"]:
            return 0, url + "\n", ""
        if command[:3] == ["git", "remote", "get-url"]:
            raise AssertionError(
                "run_push_gate must resolve the remote with `get-url --push`"
            )
        return 0, "", ""

    gate.run_command = fake_run_command
    gate.run_commit_gate = lambda: True
    return gate.run_push_gate(ref=ref, remote="origin")


def pc_verdict(allow, url, ref):
    """Allow/deny from the in-container hook's mirrored push_allowed()."""
    return PC_HOOK.push_allowed(url, ref, allow)


def bash_verdict(allow, url, ref, tmp_path):
    """Allow/deny from the generated pre-push hook, run under plain sh
    in a scratch repo whose origin points at `url`."""
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "remote", "add", "origin", url], cwd=repo, check=True)

    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)

    # A real-looking local sha: an all-zero one is git's DELETION marker,
    # which the hook refuses outright (test_ref_deletion_is_refused_*).
    stdin = f"{ref} {LOCAL_SHA} {ref} {REMOTE_SHA}\n"
    env = {**os.environ, "LMER_PUSH_ALLOW_LIST": allow}
    result = subprocess.run(
        ["sh", str(hook), "origin", url],
        input=stdin,
        cwd=repo,
        env=env,
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def test_pre_push_hook_is_posix_sh(tmp_path):
    """The generated hook declares /bin/sh and parses under `sh -n`."""
    assert PRE_PUSH_BODY.startswith("#!/bin/sh\n")
    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)
    result = subprocess.run(
        ["sh", "-n", str(hook)], capture_output=True, text=True
    )
    assert result.returncode == 0, result.stderr


@pytest.mark.parametrize("allow,url,ref,expected", CASES)
def test_all_implementations_agree(allow, url, ref, expected,
                                   tmp_path, monkeypatch, capsys):
    verdicts = {
        "gates.py": gates_verdict(allow, url, ref, monkeypatch),
        "hooks/pc.py": pc_verdict(allow, url, ref),
        "install.sh pre-push": bash_verdict(allow, url, ref, tmp_path),
    }
    assert verdicts == {name: expected for name in verdicts}, (
        f"verdict divergence for entry={allow!r} url={url!r} ref={ref!r}: "
        f"{verdicts} (expected {expected})"
    )


@pytest.mark.parametrize("bare,qualified", [
    ("main", "refs/heads/main"),
    ("feature-x", "refs/heads/feature-x"),
])
def test_bare_branch_names_normalize_only_where_the_input_is_a_branch(
        bare, qualified, monkeypatch, capsys):
    """pc.py qualifies bare names as refs/heads/<name> — its only caller
    feeds it `git branch --show-current`, so the input is a branch by
    construction. gates.py REFUSES explicit bare names: its ref parameter
    is user-supplied (`gate-push --ref`), where a short name is ambiguous
    (git resolves `v1.2.3` to refs/tags/v1.2.3 when such a tag exists), so
    normalizing there would authorize the wrong ref class. The bash hook
    never sees bare names — git feeds pre-push fully qualified refs.
    """
    allow = "group/project"
    assert pc_verdict(allow, GITLAB_SSH, bare) == pc_verdict(
        allow, GITLAB_SSH, qualified
    ) == True
    assert gates_verdict(allow, GITLAB_SSH, bare, monkeypatch) == False
    assert gates_verdict(allow, GITLAB_SSH, qualified, monkeypatch) == True


@pytest.mark.parametrize("allow", [
    "group/project",                    # bare grant, branch refs
    "group/project|refs/tags/*",        # the release-flow tag grant
    "group/project|refs/heads/*, group/project|refs/tags/*",
])
def test_ref_deletion_is_refused_by_every_implementation(allow, tmp_path,
                                                         monkeypatch, capsys):
    """Deleting a ref is never authorized, however wide the grant.

    A deletion is at least as destructive as the force push both mirrors
    already refuse, and the release flow declares published tags immutable
    (never deleted, never re-pointed). gates.py sees it as an empty `<src>`
    refspec (`:refs/tags/v0.5.0`); the pre-push hook sees git's deletion
    line — `(delete)` as the local ref with an all-zero local sha.
    """
    assert gates_verdict(allow, GITLAB_SSH, ":refs/tags/v0.5.0", monkeypatch) is False
    assert gates_verdict(allow, GITLAB_SSH, ":refs/heads/main", monkeypatch) is False

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)

    def hook_verdict(stdin):
        return subprocess.run(
            ["sh", str(hook), "origin", GITLAB_SSH],
            input=stdin,
            cwd=repo,
            env={**os.environ, "LMER_PUSH_ALLOW_LIST": allow},
            capture_output=True,
            text=True,
        )

    for ref in ("refs/tags/v0.5.0", "refs/heads/main"):
        # git's shape for a deletion, and the same line with only the
        # all-zero local sha to prove neither signal alone is relied on.
        for line in (f"(delete) {ZERO_SHA} {ref} {REMOTE_SHA}\n",
                     f"{ref} {ZERO_SHA} {ref} {REMOTE_SHA}\n"):
            result = hook_verdict(line)
            assert result.returncode == 1, result.stdout
            assert "deletion is never approved" in result.stdout


# Push-by-URL cases: (allow-list entry, URL, expected). git was handed a
# URL, so the string being matched is command-line input, not operator
# config — both mirrors anchor the match on host/path instead of a
# substring test. Refs are always an authorized branch here so the verdict
# is purely the repo half's.
URL_CASES = [
    # The two anchored identities an entry may name — both pin the HOST.
    ("github.com/group/project", GITHUB_MIRROR, True),   # host/path
    ("github.com", GITHUB_MIRROR, True),                 # host
    # A path-only entry does NOT authorize on this branch: every forge
    # lets anyone serve the same path, so a bare path matched against an
    # agent-supplied URL is the substring hole with a different prefix.
    # (Path-only grants stay valid for CONFIGURED remotes — see
    # test_named_remote_keeps_substring_semantics.)
    ("group/project", GITHUB_MIRROR, False),
    ("group/project", "https://evil.example.com/group/project.git", False),
    # A partial path component authorizes nothing.
    ("project", GITHUB_MIRROR, False),
    ("oup/project", GITHUB_MIRROR, False),
    # The attack this closes: an allowed path embedded in a foreign host's
    # path used to satisfy `repo in remote_url`.
    ("group/project", "https://evil.example.com/mirror/group/project.git", False),
    ("github.com/group/project", "https://github.com.evil.example.com/group/project.git", False),
    # Userinfo-spoof spellings: the allowed identity sits in the PATH of an
    # attacker-chosen host, so a `rsplit("@", 1)` over the whole string
    # normalizes them to the allowed identity while git dials the attacker.
    # Every one of these must be refused.
    ("github.com/group/project",
     "https://evil.example.com/x@github.com/group/project", False),
    ("github.com/group/project",
     "git@evil.invalid:x@github.com/group/project.git", False),
    ("github.com/group/project",
     "https://evil.example.com/#@github.com/group/project", False),
    ("github.com", "https://evil.example.com/x@github.com/group/project", False),
    # ...and the evil host itself is what an entry would have to name.
    ("evil.example.com/x@github.com/group/project",
     "https://evil.example.com/x@github.com/group/project", True),
    # Equivalent URL spellings normalize to the same identity.
    ("gitlab.example.com/group/project", GITLAB_SSH, True),
    ("gitlab.example.com/group/project",
     "ssh://git@gitlab.example.com:2222/group/project.git", True),
    ("gitlab.example.com/group/project",
     "https://token:x@gitlab.example.com/group/project", True),
    # A URL naming no repository (local path, bare host) authorizes nothing.
    ("group/project", "/srv/mirrors/group/project", False),
    ("github.com", "https://github.com/", False),
    ("srv/mirrors/group/project", "/srv/mirrors/group/project", False),
    # Neither does one git reads as a local path or refuses outright.
    # Without a scheme and without a `:` before the first `/` there is no
    # host to dial and no userinfo to strip, and an empty scheme is not a
    # URL at all ("protocol '' is not supported"). Both spellings used to
    # normalize to `github.com/group/project` in the generated hook while
    # gates.py refused them.
    ("github.com/group/project", "user@github.com/group/project", False),
    ("github.com", "user@github.com/group/project", False),
    ("github.com/group/project", "://github.com/group/project", False),
    ("github.com", "://github.com/group/project", False),
    # A bare hostname git cannot resolve as a remote: run_push_gate fails
    # closed, and the hook must not fall back to the CONFIGURED-remote
    # substring rule just because the string carries no URL punctuation.
    ("github.com", "github.com", False),
    # IPv6: the anchored branch pins the address exactly, in both mirrors.
    ("[2001:db8::1]/group/project", "https://[2001:db8::1]/group/project", True),
    ("[2001:db8::1]", "https://[2001:db8::1]/group/project", True),
    ("https://[2001:db8::1]/group/project",
     "https://[2001:db8::1]/group/project", True),
    ("[2001:db8::1]/group/project",
     "https://[2001:db8::9999]/group/project", False),
    ("[2001:db8::9999]", "https://[2001:db8::1]/group/project", False),
    ("[2001", "https://[2001:db8::1]/group/project", False),
    ("group/project", "https://[::1/group/project", False),
]

# The `host/path` identity each URL carries, stated as a CONSTANT rather
# than computed by any implementation: this is what `urlsplit` reports for
# the scheme forms and what git's scp-like grammar
# (`[user@]host:path`, userinfo free of `@` and `/`, host free of `:` and
# `/`) reports for the rest. None = names no repository, so nothing can
# authorize it. This table is the suite's independent expectation — the
# mirrors are checked against IT, not merely against each other.
URL_IDENTITIES = [
    (GITHUB_MIRROR, "github.com/group/project"),
    (GITLAB_SSH, "gitlab.example.com/group/project"),
    ("ssh://git@gitlab.example.com:2222/group/project.git",
     "gitlab.example.com/group/project"),
    ("https://token:x@gitlab.example.com/group/project",
     "gitlab.example.com/group/project"),
    ("HTTPS://GitHub.com/Group/Project.git", "github.com/group/project"),
    ("github.com/group/project", "github.com/group/project"),
    # Userinfo cannot appear after the first `/`: these name the evil host.
    ("https://evil.example.com/x@github.com/group/project",
     "evil.example.com/x@github.com/group/project"),
    ("git@evil.invalid:x@github.com/group/project.git",
     "evil.invalid/x@github.com/group/project"),
    # `#` starts a fragment, so this URL has no path at all.
    ("https://evil.example.com/#@github.com/group/project", None),
    # No host, or no path.
    ("/srv/mirrors/group/project", None),
    ("https://github.com/", None),
    ("github.com", None),
    ("", None),
    # No scheme and no `:` before the first `/`: git reads this as a local
    # PATH, so there is no authority and nothing to strip userinfo from.
    ("user@github.com/group/project", None),
    # Empty scheme — git refuses it ("protocol '' is not supported"), and
    # `urlsplit` finds no authority either.
    ("://github.com/group/project", None),
    # IPv6 literals. The bracket is the host boundary in every spelling git
    # accepts, and the identity is the address WITHOUT brackets — that is
    # what `urlsplit().hostname` reports, and git requires the brackets
    # outside a scheme URL to keep the address's colons apart from the
    # `host:path` delimiter.
    ("https://[2001:db8::1]/group/project", "2001:db8::1/group/project"),
    ("https://[2001:db8::1]:8443/group/project", "2001:db8::1/group/project"),
    ("ssh://git@[2001:db8::1]:22/group/project.git", "2001:db8::1/group/project"),
    ("git@[2001:db8::1]:group/project.git", "2001:db8::1/group/project"),
    ("[2001:db8::1]/group/project", "2001:db8::1/group/project"),
    ("https://[::1]/group/project", "::1/group/project"),
    # No path, so no repository — the same rule as `https://github.com/`.
    ("https://[2001:db8::1]", None),
    ("[2001:db8::1]", None),
    # An unclosed bracket is not a URL at all (`urlsplit` raises here) and
    # names no host: `https://[::1/group/project` must NOT be read as the
    # host `[` carrying the path `group/project`.
    ("https://[::1/group/project", None),
    ("[::1/group/project", None),
]


# (entry spelling, the single host that entry names). The property guards
# below drive every one of these against every URL: an entry may authorize
# only when the host it names IS the host git dials. The IPv6 entries are
# in URL spelling because that is the shape that leaked — `https://[addr]`
# normalized to the host `[2001` in both mirrors, so ONE such entry
# authorized every address sharing that first hextet.
ENTRY_HOSTS = [
    ("github.com", "github.com"),
    ("gitlab.example.com", "gitlab.example.com"),
    ("evil.example.com", "evil.example.com"),
    ("evil.invalid", "evil.invalid"),
    ("https://[2001:db8::1]", "2001:db8::1"),
    ("https://[2001:db8::9999]", "2001:db8::9999"),
    ("[2001:db8::1]", "2001:db8::1"),
    ("https://[::1]", "::1"),
    ("[::2]", "::2"),
]


def independent_host(url):
    """The host git will dial, parsed independently of everything under test.

    `urlsplit` for the scheme forms; git's own scp-like grammar otherwise.
    Used by the property guard below — a bug the three mirrors SHARE cannot
    be caught by comparing them to each other, only by comparing them to an
    outside answer.
    """
    url = url.strip()
    if "://" in url:
        try:
            return (urlsplit(url).hostname or "").lower()
        except ValueError:
            return ""       # e.g. an unclosed IPv6 bracket: not a URL
    # git requires an IPv6 literal to be BRACKETED outside a scheme URL,
    # "to avoid ambiguity with a local path containing a colon" — so the
    # bracket, not the first colon, is where the host ends.
    match = re.match(r"^(?:[^@/]+@)?\[([^\[\]/]+)\](?:[:/]|$)", url)
    if match:
        return match.group(1).lower()
    if url.partition("/")[0].startswith("["):
        return ""           # malformed bracket: names no host
    match = re.match(r"^(?:[^@/]+@)?([^:/]+):", url)
    if match:
        return match.group(1).lower()
    host = url.partition("/")[0]
    return host.lower() if re.fullmatch(r"[^@/:]+", host) else ""


@pytest.mark.parametrize("url,expected", URL_IDENTITIES)
def test_url_identity_matches_the_independently_stated_expectation(url, expected):
    """gates.py's normalizer against hand-written expectations.

    Stating the answers as constants is the point: the previous suite only
    asked the three mirrors to agree, and they agreed on a wrong answer for
    every userinfo-spoof spelling.
    """
    assert GateSystem()._normalize_remote_url(url) == expected


@pytest.mark.parametrize("url,_expected", URL_IDENTITIES)
def test_the_authorized_host_is_the_host_git_would_dial(
        url, _expected, tmp_path, monkeypatch, capsys):
    """The property a shared bug violates: on the push-by-URL branch, an
    entry naming a host OTHER than the one git dials never authorizes.

    Checked against `independent_host` (urlsplit / git's scp grammar), so
    it holds whatever the implementations happen to do — and it is checked
    in both mirrors that have this branch.
    """
    for entry, names in ENTRY_HOSTS:
        if names == independent_host(url):
            continue  # this entry legitimately names the dialled host
        allow = f"{entry}|refs/heads/*"
        monkeypatch.setenv("LMER_PUSH_ALLOW_LIST", allow)
        gate = GateSystem()
        gate.run_command = lambda command, check=True: (1, "", "no such remote")
        gate.run_commit_gate = lambda: True
        assert gate.run_push_gate(ref="refs/heads/main", remote=url) is False, (
            f"gates.py authorized entry {entry!r} for {url!r}, which git "
            f"dials at {independent_host(url)!r}"
        )

        repo = tmp_path / "repo"
        repo.mkdir(exist_ok=True)
        subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
        hook = tmp_path / "pre-push"
        hook.write_text(PRE_PUSH_BODY)
        result = subprocess.run(
            ["sh", str(hook), url, url],
            input=f"refs/heads/main {LOCAL_SHA} refs/heads/main {REMOTE_SHA}\n",
            cwd=repo,
            env={**os.environ, "LMER_PUSH_ALLOW_LIST": allow},
            capture_output=True,
            text=True,
        )
        assert result.returncode == 1, (
            f"pre-push hook authorized entry {entry!r} for {url!r}, which "
            f"git dials at {independent_host(url)!r}: {result.stdout}"
        )


@pytest.mark.parametrize("url,_expected",
                         [pair for pair in URL_IDENTITIES if pair[0].strip()])
def test_the_configured_remote_branch_pins_that_host_too(
        url, _expected, tmp_path, monkeypatch, capsys):
    """The same property, over the CONFIGURED-remote branch.

    That branch is deliberately wider — prefixes, wildcard domains and
    host-less paths all grant there — but a HOST-naming entry must still
    only authorize the host git actually dials. The property guard above
    drives the push-by-URL branch only, and that is precisely where a
    shared normalization bug hid: `user@github.com/group/project`, which
    git reads as a local path, normalized to a `github.com` identity in all
    three implementations and so was granted by an entry naming a host the
    push never reaches.

    The entries here are bare hosts, so no legitimate wildcard or
    host-less grant is being asserted away — only "an entry naming host A
    never authorizes a push git sends to host B".
    """
    ref = "refs/heads/main"
    for index, (entry, names) in enumerate(ENTRY_HOSTS):
        if names == independent_host(url):
            continue  # this entry legitimately names the dialled host
        allow = f"{entry}|refs/heads/*"
        dialled = independent_host(url) or "(no host)"
        scratch = tmp_path / f"entry{index}"
        scratch.mkdir(exist_ok=True)
        verdicts = {
            "gates.py": gates_verdict(allow, url, ref, monkeypatch),
            "hooks/pc.py": pc_verdict(allow, url, ref),
            "install.sh pre-push": bash_verdict(allow, url, ref, scratch),
        }
        assert verdicts == {name: False for name in verdicts}, (
            f"entry {entry!r} authorized configured remote {url!r}, which "
            f"git dials at {dialled}: {verdicts}"
        )


@pytest.mark.parametrize("allow,url,expected", URL_CASES)
def test_push_by_url_matching_is_anchored_in_both_mirrors(
        allow, url, expected, tmp_path, monkeypatch, capsys):
    entry = f"{allow}|refs/heads/*"
    monkeypatch.setenv("LMER_PUSH_ALLOW_LIST", entry)
    gate = GateSystem()
    # No configured remote: `--remote <url>` takes the push-by-URL branch.
    gate.run_command = lambda command, check=True: (1, "", "no such remote")
    gate.run_commit_gate = lambda: True

    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)
    hook_result = subprocess.run(
        # git hands a URL push the URL as BOTH argv[1] and argv[2].
        ["sh", str(hook), url, url],
        input=f"refs/heads/main {LOCAL_SHA} refs/heads/main {REMOTE_SHA}\n",
        cwd=repo,
        env={**os.environ, "LMER_PUSH_ALLOW_LIST": entry},
        capture_output=True,
        text=True,
    )

    verdicts = {
        "gates.py": gate.run_push_gate(ref="refs/heads/main", remote=url),
        "install.sh pre-push": hook_result.returncode == 0,
    }
    assert verdicts == {name: expected for name in verdicts}, (
        f"push-by-URL verdict divergence for entry={entry!r} url={url!r}: "
        f"{verdicts} (expected {expected})"
    )


def test_gate_checks_the_pushurl_not_the_fetch_url(tmp_path, monkeypatch, capsys):
    """A configured `remote.<name>.pushurl` is where git pushes; the gate
    must authorize THAT url.

    Driven against a real repository and real `git remote get-url` — a
    stubbed run_command cannot prove the `--push` flag is passed, which is
    precisely why the defect survived the mirror-vs-mirror parity suite.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "remote", "add", "origin", GITHUB_MIRROR],
                   cwd=repo, check=True)
    subprocess.run(["git", "config", "remote.origin.pushurl",
                    "https://evil.example.invalid/x.git"], cwd=repo, check=True)

    def verdict(allow):
        monkeypatch.setenv("LMER_PUSH_ALLOW_LIST", allow)
        gate = GateSystem()
        gate.project_root = repo  # run_command runs with cwd=project_root
        gate.run_commit_gate = lambda: True
        return gate.run_push_gate(ref="refs/heads/main", remote="origin")

    # The fetch url is on the allow list; the PUSH url is not.
    assert verdict("github.com/group/project") is False
    # ...and naming the push url authorizes it, proving the gate read that
    # url rather than simply failing on everything.
    assert verdict("evil.example.invalid/x") is True

    # The generated hook is fed the push url by git itself ($2), so it is
    # right by construction — pin that it stays keyed on $2.
    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)
    result = subprocess.run(
        ["sh", str(hook), "origin", "https://evil.example.invalid/x.git"],
        input=f"refs/heads/main {LOCAL_SHA} refs/heads/main {REMOTE_SHA}\n",
        cwd=repo,
        env={**os.environ,
             "LMER_PUSH_ALLOW_LIST": "github.com/group/project|refs/heads/*"},
        capture_output=True,
        text=True,
    )
    assert result.returncode == 1, result.stdout


def test_detached_head_refuses_instead_of_matching_refs_heads_star(
        tmp_path, monkeypatch, capsys):
    """`git branch --show-current` exits 0 with EMPTY stdout on a detached
    HEAD. Interpolating that gives the literal "refs/heads/", and
    `fnmatch("refs/heads/", "refs/heads/*")` is True — `*` matches empty —
    so a bare allow-list entry would authorize a ref naming no branch.
    Both python mirrors must refuse instead."""
    monkeypatch.setenv("LMER_PUSH_ALLOW_LIST", "group/project")
    gate = GateSystem()

    def fake_run_command(command, check=True):
        if command[:4] == ["git", "remote", "get-url", "--push"]:
            return 0, GITLAB_SSH + "\n", ""
        if command[:3] == ["git", "branch", "--show-current"]:
            return 0, "\n", ""  # detached HEAD
        return 0, "", ""

    gate.run_command = fake_run_command
    gate.run_commit_gate = lambda: True
    assert gate.run_push_gate(ref=None, remote="origin") is False
    assert "detached HEAD" in capsys.readouterr().out

    # hooks/pc.py's push_allowed() has the same shape; its caller is what
    # must not hand it an empty branch (see main()). The URL is a real repo
    # URL (granted by the `group/project` entry through the host-less rule)
    # rather than the bare entry text: since #107 the repo half is parsed
    # into host+path instead of substring-matched, so `group/project` as a
    # URL would now be read as host `group`, and this test would fail for a
    # reason that has nothing to do with the empty ref it exists to pin.
    assert PC_HOOK.push_allowed(GITLAB_SSH, "") is True, (
        "push_allowed itself still normalizes '' — the guard belongs in the "
        "caller, and this pins which side owns it"
    )
    source = PC_HOOK_PATH.read_text()
    assert "if not branch:" in source, (
        "hooks/pc.py must refuse an empty `git branch --show-current` before "
        "calling push_allowed"
    )


def test_pc_hook_pushes_the_remote_it_authorized():
    """hooks/pc.py must push to the remote whose URL it gated on.

    It authorizes `git remote get-url --push origin`, so the push has to
    name `origin` explicitly: a bare `git push` resolves its remote through
    branch.<name>.pushRemote → remote.pushDefault → branch.<name>.remote,
    and either of the first two sends the commit to a remote the allow-list
    check never looked at — the same authorize-one-target-dial-another
    shape as gating the fetch url instead of the push url.
    """
    source = PC_HOOK_PATH.read_text()
    assert '["git", "push", "origin", branch]' in source, (
        "hooks/pc.py must push to the remote and ref it authorized "
        "(`git push origin <branch>`)"
    )
    assert '["git", "push"])' not in source, (
        "a bare `git push` can be redirected by remote.pushDefault / "
        "branch.<name>.pushRemote to a remote the gate never checked"
    )


def test_named_remote_keeps_substring_semantics(monkeypatch, capsys):
    """The anchoring is scoped to the push-by-URL branch. A CONFIGURED
    remote's URL was set up by the operator, so the historical substring
    rule stays — tightening it would silently invalidate deployed
    allow lists that name a path fragment."""
    assert gates_verdict("mirror/group/project",
                         "https://evil.example.com/mirror/group/project.git",
                         "refs/heads/main", monkeypatch) is True


def test_pre_push_hook_fails_closed_without_a_remote_url(tmp_path):
    """No resolvable remote and no URL argument → the hook BLOCKS (exit 1).
    Exiting 0 there would skip the allow-list evaluation for push-by-URL."""
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)

    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)
    result = subprocess.run(
        ["sh", str(hook), "nosuch-remote"],
        input=f"refs/heads/main {LOCAL_SHA} refs/heads/main {REMOTE_SHA}\n",
        cwd=repo,
        env={**os.environ, "LMER_PUSH_ALLOW_LIST": "group/project"},
        capture_output=True,
        text=True,
    )
    assert result.returncode == 1
    assert "cannot determine the remote URL" in result.stdout


def test_pre_push_hook_gates_push_by_url_via_arg2(tmp_path):
    """Push-by-URL: git passes the URL as $2 with no configured remote —
    the hook must evaluate the allow list against it, both directions."""
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    hook = tmp_path / "pre-push"
    hook.write_text(PRE_PUSH_BODY)
    stdin = f"refs/heads/main {LOCAL_SHA} refs/heads/main {REMOTE_SHA}\n"

    def push_by_url(url, allow="github.com/group/project"):
        return subprocess.run(
            ["sh", str(hook), url, url],
            input=stdin,
            cwd=repo,
            env={**os.environ, "LMER_PUSH_ALLOW_LIST": allow},
            capture_output=True,
            text=True,
        ).returncode

    assert push_by_url(GITHUB_MIRROR) == 0
    assert push_by_url("https://github.com/attacker/repo.git") == 1
    # The entry must name the host on this branch: a path-only grant would
    # authorize the same path on any forge.
    assert push_by_url(GITHUB_MIRROR, allow="group/project") == 1
