"""Repo-half matching for the gate-push allow list (#107).

This module owns the **repo half** of an allow-list entry — the part that
decides *which repository* a push may land on. The **ref half**
(``repo|refpattern``, the branch-only default, refspec safety) is owned by
:mod:`lmer_cli.gates`, which splits each entry before asking this module
about the repo half. Both halves must grant for a push to be authorized.

Entries come from two sources, unioned (any single entry granting the
target allows the push — there are no deny entries):

* the ``LMER_PUSH_ALLOW_LIST`` environment variable (comma-separated), and
* an optional top-level ``push_allow`` list in the active taskdef's per-task
  ``task.yaml`` — the same manifest as ``masterplan:`` (see docs/TASKDEFS.md),
  but resolved from the **trusted taskdef tiers only**: the
  ``LMER_TASKDEF_PATHS`` directories, then the shipped (built-in) taskdef
  root. The work-repo tiers (``{work_repo}/{host}/{project}/taskdef/`` and
  ``{work_repo}/taskdef/``) are deliberately excluded from push-grant
  resolution: agents push to the work repo routinely, so a ``task.yaml``
  smuggled into it must never be able to grant itself push targets. Those
  tiers keep their normal first-match precedence for benign keys like
  ``masterplan:`` — the exclusion is specific to ``push_allow``. The
  ``LMER_TASKDEF_DIR``/``LMER_TASK_INSTRUCTIONS`` pre-resolved fallbacks
  are skipped for the same reason (they may point into a work-repo tier).
  Reading the manifest is fail-soft: a missing, unreadable, or malformed
  manifest contributes no entries and never breaks the gate.

  NOTE the key is **top-level** ``push_allow``, and nothing else in a
  ``task.yaml`` is a grant. The documentation-only block that
  ``taskdef/release/task.yaml`` carries (roles a release session requires,
  resolved per-adopter) is spelled ``needs.push_targets`` precisely so a
  reader — or a diff that dedents it — cannot turn documentation into a
  permission. Belt and braces: only a top-level list of **strings**
  contributes entries, so even a block that landed at the top level under
  this key would grant nothing.

  The two SOURCES are not mirrored. ``hooks/pc.py`` and the pre-push hook
  generated by ``hooks/install.sh`` read ``LMER_PUSH_ALLOW_LIST`` only —
  they run standalone and cannot resolve a taskdef — so a taskdef-granted
  target is allowed by ``gate-push`` and refused by those two. That is the
  safe direction (they are stricter, never laxer), and the parity suite
  pins the GRAMMAR at all three points rather than the source set.

Entry grammar — the repo half of each entry is one of:

* **Exact repo** — a full repo URL or ``host/project`` path::

      git@gitlab.example.com:group/project.git
      https://gitlab.example.com/group/project
      gitlab.example.com/group/project

  All three normalize to the same rule: host ``gitlab.example.com``,
  project path ``group/project`` (which, like every path rule, also covers
  projects nested beneath it, e.g. ``group/project/sub``).

* **Whole host** — a bare hostname (no ``/``) allows any project there::

      gitlab.example.com

* **Wildcard domain** — ``*.example.com`` allows any project on any host
  ending in ``.example.com``. Subdomains only: the apex ``example.com``
  needs its own entry, and the ``.`` boundary is enforced
  (``evilexample.com`` never matches).

* **Host + project prefix** — ``gitlab.example.com/group`` allows any
  project on that host whose path starts with the ``group`` segment.
  Prefixes are segment-boundary safe: ``group`` matches ``group/project``
  but NOT ``groupfoo/x``. A wildcard host combines: ``*.example.com/group``.

* **Host-less project path** (legacy) — an entry containing ``/`` whose
  first segment does not look like a hostname (no dot, not ``localhost``),
  e.g. ``org/repo``, matches that project path on **any** host, again at
  segment boundaries (``org/repo`` matches ``org/repo`` and ``org/repo/sub``
  but not ``org/repo2``). This keeps pre-#107 allowlists working; prefer
  host-qualified entries for new configuration.

Matching details:

* **IPv6 hosts are written BRACKETED** — ``[2001:db8::1]``,
  ``[2001:db8::1]/group/project``, ``https://[2001:db8::1]/group/project``,
  ``git@[2001:db8::1]:group/project.git`` — and all of those normalize to
  the same identity, host ``2001:db8::1``, exactly as
  ``urlsplit().hostname`` reports it. The brackets are git's own
  requirement outside a ``scheme://`` URL (they are what separates the
  address's colons from the ``host:path`` delimiter), so the unbracketed
  spelling is NOT accepted as an entry: ``2001:db8::1/group/project``
  parses as host ``2001``. An unclosed or empty bracket names no host at
  all and is refused. Addresses compare as text, so an entry must spell
  the address the way the remote URL does.
* Hostnames compare case-insensitively; project paths case-sensitively.
* URL schemes, ``user@`` prefixes, the SSH ``host:path`` colon, a trailing
  ``.git``, and trailing slashes are stripped from both entries and remote
  URLs before comparison, so SSH and HTTPS spellings of the same repo are
  interchangeable.

Two matching MODES, and the difference is the whole security story:

* **Configured remote** (``exact_identity=False``) — the URL came from the
  operator's own git config, so the full grammar above applies.
* **Push-by-URL** (``exact_identity=True``) — the URL came from the command
  line (``gate-push --remote https://…``), i.e. from the agent rather than
  the operator. Here an entry authorizes only when it names the **exact
  identity git will dial**: the full ``host/path`` or the bare ``host``.
  Prefix rules, wildcard domains and host-less legacy paths grant nothing
  on this branch — each of them would let an attacker-chosen host inherit a
  grant written for somebody else. This is the pre-#107 rule
  (``GateSystem._url_entry_authorizes``) preserved exactly: the grammar
  added by #107 never widens the adversarial branch.

An unparsable target (e.g. a local filesystem remote) is refused rather
than guessed at; the caller reports it.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import List, Optional, Tuple
from urllib.parse import urlparse


def env_allow_list() -> List[str]:
    """Entries from the ``LMER_PUSH_ALLOW_LIST`` env var (comma-separated).

    Returns an empty list if not configured (no repos auto-allowed).
    """
    raw = os.environ.get("LMER_PUSH_ALLOW_LIST", "")
    return [entry.strip() for entry in raw.split(",") if entry.strip()]


def _trusted_taskdef_dirs() -> List[Path]:
    """Taskdef tiers allowed to carry push grants, in precedence order.

    Only the ``LMER_TASKDEF_PATHS`` directories and the shipped taskdef root
    qualify — never the work-repo tiers, and never the pre-resolved
    ``LMER_TASKDEF_DIR``/``LMER_TASK_INSTRUCTIONS`` fallbacks (which may
    point into a work-repo tier). See the module docstring for the threat
    model behind the exclusion.
    """
    # Deferred like masterplan's own imports: keep this module importable
    # and the env-only paths testable without the taskdef search loaded.
    from lmer_cli.container.taskdefs import builtin_taskdef_root

    dirs: List[Path] = []
    for p in os.environ.get("LMER_TASKDEF_PATHS", "").split(":"):
        p = p.strip()
        if p:
            dirs.append(Path(p))
    dirs.append(builtin_taskdef_root())
    return dirs


def taskdef_allow_source() -> Tuple[List[str], Optional[Path]]:
    """``push_allow`` entries from the active taskdef's ``task.yaml``, plus
    the manifest path they came from (for the gate's grant/refusal output).

    The manifest is resolved for the active task (``LMER_TASK``/
    ``LMER_TASKDEF``) from the trusted tiers only (:func:`_trusted_taskdef_dirs`)
    — a ``task.yaml`` in a work-repo tier must never grant. Accepts a
    top-level YAML list of strings (or a single comma-separated string);
    non-string members are ignored so a nested documentation block's shape
    (``needs.push_targets``, a list of mappings) can never be read as a
    grant even if it moved to the top level.
    Fail-soft: any missing/unreadable/malformed manifest yields
    ``([], None)`` — a bad ``task.yaml`` must never grant nor crash the gate.
    """
    try:
        from lmer_cli.container.masterplan import TASK_MANIFEST

        taskdef_name = os.environ.get("LMER_TASK") or os.environ.get("LMER_TASKDEF")
        if not taskdef_name:
            return [], None
        manifest = None
        for search_dir in _trusted_taskdef_dirs():
            candidate = search_dir / taskdef_name / TASK_MANIFEST
            if candidate.exists():
                manifest = candidate
                break
        if manifest is None:
            return [], None
        import yaml

        data = yaml.safe_load(manifest.read_text())
    except Exception:
        return [], None
    if not isinstance(data, dict):
        return [], None
    value = data.get("push_allow")
    if isinstance(value, str):
        value = value.split(",")
    if not isinstance(value, list):
        return [], None
    # Strings only: a mapping (the `needs.push_allow` role shape) or any
    # other node contributes nothing rather than being stringified into a
    # junk entry.
    entries = [entry.strip() for entry in value
               if isinstance(entry, str) and entry.strip()]
    return entries, manifest


def taskdef_allow_list() -> List[str]:
    """``push_allow`` entries from the active taskdef's ``task.yaml``.

    Thin wrapper over :func:`taskdef_allow_source` for callers that don't
    need the manifest path.
    """
    return taskdef_allow_source()[0]


def _split_bracketed(authority: str) -> Tuple[str, str]:
    """``(host, path)`` for a BRACKETED IPv6 authority, ``("", "")`` if it
    is not one.

    Outside a ``scheme://`` URL git requires an IPv6 literal to be
    bracketed — "to avoid ambiguity with a local path containing a colon"
    — and the bracket is what tells the address's colons from the
    ``host:path`` delimiter. So the host is exactly what the brackets
    enclose, and only ``:path`` (scp-like), ``/path`` or nothing may
    follow.

    The normalized host is the address WITHOUT brackets, which is what
    ``urlsplit().hostname`` yields for the ``scheme://`` spelling — that is
    what makes ``[2001:db8::1]``, ``https://[2001:db8::1]`` and
    ``git@[2001:db8::1]:group/project`` one identity everywhere.

    An unclosed, empty or trailing-junk bracket names no host and is
    refused, mirroring the ValueError ``urlsplit`` raises for the same
    shapes.
    """
    close = authority.find("]")
    if close < 0:
        return "", ""
    host = authority[1:close]
    if not host:
        return "", ""
    tail = authority[close + 1:]
    if tail == "":
        return host, ""
    if tail[0] in ":/":
        return host, tail[1:]
    return "", ""


def split_target(text: str) -> Tuple[str, str]:
    """Normalize a repo URL or ``host/path`` string into ``(host, path)``.

    Handles ``scheme://host/path``, SCP-like ``user@host:path``, and bare
    ``host[/path]`` forms; strips ``user@``, a trailing ``.git``, and
    trailing slashes; lowercases the host. Either element may come back
    empty when the input does not carry it.

    Userinfo is stripped only where it may legally appear — inside the
    authority. ``urlparse`` reads the authority for ``scheme://`` URLs, and
    the SCP-like branch splits on the FIRST ``:``, whose left side cannot
    contain ``/``. A host carrying an allowed identity in its *path*
    (``https://evil.example.com/x@github.com/group/project``) therefore
    normalizes to ``evil.example.com``, never to the embedded identity.
    The bare form has no authority at all — git reads a string with no
    scheme and no ``:`` before the first ``/`` as a local PATH — so an
    ``@`` there names nothing and the input is refused rather than read as
    userinfo (the same ``[^@/:]+`` rule ``GateSystem._normalize_remote_url``
    applies, and what tests/test_push_allow_grammar_parity.py's identity
    table states for ``user@github.com/group/project``).

    NEVER raises. Every allow-list ENTRY reaches this function too, so a
    malformed one must fail to grant without aborting the entries after it.
    """
    t = text.strip().rstrip("/")
    if "://" in t:
        try:
            parsed = urlparse(t)
            host = parsed.hostname or ""
        except ValueError:
            # urlsplit/urlparse raises on an unmatched IPv6 bracket
            # (`https://[::1/g/p`). Letting that propagate would take the
            # whole gate down on one bad entry — and, since entries are
            # evaluated in order, make authorization depend on where the
            # bad entry sits in the list. No identity: grants nothing,
            # refuses nothing else (the fail-closed contract in
            # _parse_push_allow_entry and docs/LMER-CLI.md).
            return "", ""
        path = parsed.path
    else:
        authority = t
        if "@" in t:
            user, _, after_at = t.partition("@")
            if after_at.startswith("[") and "/" not in user:
                authority = after_at  # scp-like [user@][ipv6]:path
        if authority.startswith("["):
            # An IPv6 literal, and only _split_bracketed may resolve it:
            # the colon logic below would cut the address at its first
            # colon, collapsing every `2001:…` address to one host.
            host, path = _split_bracketed(authority)
            if not host:
                return "", ""
        elif "]" in authority.split("/", 1)[0]:
            # A stray `]` with no `[` — refused for the same reason
            # urlsplit refuses it: this is not an authority.
            return "", ""
        else:
            head, path = t, ""
            first_seg = t.split("/", 1)[0]
            if ":" in first_seg:
                # SCP-like syntax: [user@]host:path — userinfo legally
                # precedes the host here, so strip it.
                head, path = t.split(":", 1)
                if "@" in head:
                    head = head.rsplit("@", 1)[1]
            else:
                if "/" in t:
                    head, path = t.split("/", 1)
                if "@" in head:
                    return "", ""  # local path, not an authority — above
            host = head
    path = path.strip("/")
    path = path.removesuffix(".git")
    return host.lower(), path.strip("/")


def _looks_like_host(segment: str) -> bool:
    """True when an entry's first path segment plausibly names a host."""
    return "." in segment or segment == "localhost" or segment.startswith("*")


def _entry_rule(entry: str) -> Optional[Tuple[Optional[str], str]]:
    """Classify an entry into ``(host_pattern | None, path_prefix)``.

    ``host_pattern is None`` marks a legacy host-less project path (matches
    on any host). Returns None for an empty entry.
    """
    e = entry.strip()
    if not e:
        return None
    first_seg = e.split("/", 1)[0]
    explicit_host = "://" in e or "@" in first_seg or ":" in first_seg
    if not explicit_host and "/" in e and not _looks_like_host(first_seg):
        # Legacy host-less project path, e.g. "org/repo".
        return None, e.rstrip("/").removesuffix(".git")
    host, path = split_target(e)
    if not host:
        return None
    return host, path


def _host_matches(pattern: str, host: str) -> bool:
    if not host:
        return False
    pattern = pattern.lower()
    if pattern.startswith("*."):
        return host.endswith(pattern[1:])  # ".example.com" — dot boundary kept
    return host == pattern


def _path_matches(prefix: str, path: str) -> bool:
    if not prefix:
        return True  # host-only rule: any project on the host
    return path == prefix or path.startswith(prefix + "/")


def entry_allows(entry: str, host: str, path: str,
                 exact_identity: bool = False) -> bool:
    """True when a single allowlist entry grants ``(host, path)``.

    ``exact_identity=True`` is the push-by-URL branch: only an entry naming
    the full ``host/path`` or the bare ``host`` grants, so the grammar's
    prefix/wildcard/host-less rules cannot be turned against an
    agent-supplied URL (see the module docstring).
    """
    rule = _entry_rule(entry)
    if rule is None:
        return False
    entry_host, entry_prefix = rule
    if exact_identity:
        if entry_host is None or entry_host.startswith("*."):
            # Neither a host-less path nor a wildcard domain names the one
            # host git will dial — both authorize nothing here.
            return False
        if entry_host != host:
            return False
        return entry_prefix == "" or entry_prefix == path
    if entry_host is None:
        return _path_matches(entry_prefix, path)
    return _host_matches(entry_host, host) and _path_matches(entry_prefix, path)


def granting_entry(remote_url: str, entries: List[str],
                   exact_identity: bool = False) -> Optional[str]:
    """The first entry that grants a push to ``remote_url``, or None.

    Union semantics — any single entry suffices. The winning entry is
    surfaced so gate-push can name it (and its source) when it allows.
    A URL that does not parse into host+path grants nothing: the gate
    fails closed and reports the unusable target.
    """
    host, path = split_target(remote_url)
    if not host or not path:
        return None
    for entry in entries:
        if entry_allows(entry, host, path, exact_identity=exact_identity):
            return entry
    return None


def target_allowed(remote_url: str, entries: List[str],
                   exact_identity: bool = False) -> bool:
    """True when any entry grants a push to ``remote_url`` (union semantics)."""
    return granting_entry(remote_url, entries,
                          exact_identity=exact_identity) is not None


def example_entry(remote_url: str) -> str:
    """A concrete allowlist entry that would grant ``remote_url``.

    Used by gate-push's refusal message so the fix is copy-pasteable. The
    ref half is included because a bare entry authorizes branch refs only.

    An IPv6 host is re-BRACKETED: the normalized host is the bare address,
    but the bare spelling is not a legal entry — ``2001:db8::1/group/proj``
    would be read as host ``2001`` under the scp-like rule (git requires
    the brackets for exactly that reason). Printing the unbracketed form
    would hand the operator an entry that earns a second refusal.
    """
    host, path = split_target(remote_url)
    if host and path:
        if ":" in host:
            host = f"[{host}]"
        return f"{host}/{path}"
    return remote_url.strip()
