#!/bin/bash
# lib.sh — shared helpers for the release rehearsal rig (see README.md in
# this directory; that document is the frozen design).
#
# Sourced by stand-up.sh and by the later rehearsal scripts (negative
# tag-verification tests, leg-2 dry run), which only consume what is
# defined here:
#   - production-target guard (offline; runs before any network call)
#   - GitHub API wrapper + Actions run/job polling
#   - TestPyPI file listing, GitHub release lookup
#   - evidence writer / parser / offline verifier
#
# Also executable directly for the offline evidence re-check:
#   Ctl/rehearsal/lib.sh --verify-evidence <file>
#
# No rig identity is hard-coded here: repo, project, environment, and
# credentials all arrive via LMER_REHEARSAL_* variables (rig.env).

REHEARSAL_LIB_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REHEARSAL_ROOT=${REHEARSAL_ROOT:-$(cd -- "${REHEARSAL_LIB_DIR}/../.." && pwd)}

REHEARSAL_GITHUB_API=${REHEARSAL_GITHUB_API:-https://api.github.com}
REHEARSAL_TESTPYPI_URL=${REHEARSAL_TESTPYPI_URL:-https://test.pypi.org}

# Same path as production, deliberately (README: trusted-publisher binding).
REHEARSAL_WORKFLOW_PATH=".github/workflows/release.yml"
REHEARSAL_PUBLISH_JOB="publish-pypi"

# The rehearsal-only credential variables required by rig-touching modes
# (README: Credential isolation). R14: when any is absent, rig-touching
# modes SKIP-CLEAN. LMER_REHEARSAL_TESTPYPI_TOKEN is deliberately NOT
# listed: no rig script reads it — TestPyPI verification uses the tokenless
# read-only JSON API and publishing goes through the trusted publisher
# (OIDC) — so it must not gate anything.
REHEARSAL_ENV_VARS=(
    LMER_REHEARSAL_GITHUB_TOKEN
    LMER_REHEARSAL_SIGNING_KEY
)

# Evidence scenarios (README: Evidence format).
REHEARSAL_SCENARIOS="negative-unsigned-tag negative-wrong-signer negative-not-main-head leg2-dry-run"

rehearsal_err() {
    printf '%s\n' "$*" >&2
}

rehearsal_refuse() {
    printf 'REFUSED: %s\n' "$*" >&2
    return 1
}

# ---------------------------------------------------------------------------
# Production-target guard — fully offline, must run before any network call.
# The rig is rehearsal-only: it never touches the production mirror
# (lmer2/lmer), the production PyPI project (lmer), pypi.org, the
# production release PAT, or the production release signing key.
# ---------------------------------------------------------------------------

rehearsal_guard_repo() {
    local repo="${1:-}"
    [[ -z "$repo" ]] && return 0
    local lower=${repo,,}
    local name=${lower##*/}
    if [[ "$lower" == "lmer2/lmer" || "$name" == "lmer" ]]; then
        rehearsal_refuse "'$repo' is a production repo target; the rehearsal rig only touches its own scratch repo (e.g. <bot>/lmer-rehearsal)"
        return 1
    fi
    return 0
}

rehearsal_guard_project() {
    local project="${1:-}"
    [[ -z "$project" ]] && return 0
    if [[ "${project,,}" == "lmer" ]]; then
        rehearsal_refuse "'$project' is the production PyPI project name; the rehearsal project must be unmistakably non-production (e.g. lmer-rehearsal)"
        return 1
    fi
    return 0
}

rehearsal_guard_url() {
    local url="${1:-}"
    [[ -z "$url" ]] && return 0
    local host=${url#*://}
    host=${host%%[/:]*}
    host=${host,,}
    case "$host" in
        test.pypi.org)
            return 0
            ;;
        pypi.org|*.pypi.org)
            rehearsal_refuse "'$host' is production PyPI; the rehearsal rig only talks to test.pypi.org"
            return 1
            ;;
    esac
    return 0
}

rehearsal_guard_credentials() {
    # A rehearsal shell must not carry production release credentials at
    # all — rig credentials are rehearsal-only by name (LMER_REHEARSAL_*),
    # and the presence of a production release variable means this
    # environment could reach production. Refuse outright.
    local v
    for v in LMER_RELEASE_SIGNING_KEY LMER_RELEASE_GITHUB_TOKEN LMER_RELEASE_GITHUB_PAT RELEASE_GITHUB_PAT; do
        if [[ -n "${!v:-}" ]]; then
            rehearsal_refuse "production release credential variable $v is set; the rehearsal rig never runs with production credentials in its environment"
            return 1
        fi
    done
    # The throwaway rehearsal key must never be the production key mount
    # (CONTAINER_RELEASE_SIGNING_KEY_PATH in src/lmer_cli/mounts.py).
    case "${LMER_REHEARSAL_SIGNING_KEY:-}" in
        /release-signing-key|/release-signing-key/*)
            rehearsal_refuse "LMER_REHEARSAL_SIGNING_KEY points at the production release key mount (/release-signing-key); use a throwaway key generated by stand-up.sh"
            return 1
            ;;
    esac
    return 0
}

# rehearsal_guard <repo> <project> [url ...] — the whole guard in one call.
rehearsal_guard() {
    local repo="${1:-}" project="${2:-}"
    rehearsal_guard_credentials || return 1
    rehearsal_guard_repo "$repo" || return 1
    rehearsal_guard_project "$project" || return 1
    if (($# > 2)); then
        shift 2
        local url
        for url in "$@"; do
            rehearsal_guard_url "$url" || return 1
        done
    fi
    return 0
}

# ---------------------------------------------------------------------------
# R14 skip-clean — rig-touching modes with no rig env vars do nothing,
# loudly and successfully, so the scripts verify in a sandbox.
# ---------------------------------------------------------------------------

# Print the names of the unset rig credential variables, one per line.
rehearsal_missing_env() {
    local v
    for v in "${REHEARSAL_ENV_VARS[@]}"; do
        if [[ -z "${!v:-}" ]]; then
            printf '%s\n' "$v"
        fi
    done
    return 0
}

rehearsal_skip_clean() {
    local mode="$1"
    shift
    echo "SKIP-CLEAN (${mode}): rehearsal rig env vars absent — nothing to touch."
    echo "  missing: $*"
    echo "  To enable the rig, copy Ctl/rehearsal/rig.env.example to Ctl/rehearsal/rig.env and fill it in."
    echo "  Exiting 0 by design (R14): the rig is optional in sandboxes."
}

# ---------------------------------------------------------------------------
# GitHub API (Actions run/job polling, release lookup)
# ---------------------------------------------------------------------------

# The Authorization header rides a 0600 file (curl -H @file), never argv —
# a command line is world-readable via /proc/*/cmdline, and the pollers
# re-invoke curl every few seconds. The rig scripts call
# rehearsal_gh_auth_setup once, in the parent shell, before their first
# API call (rehearsal_gh_api mostly runs inside command substitutions,
# where a lazily created path could not persist), and remove the file
# from their EXIT traps via rehearsal_gh_auth_cleanup.
REHEARSAL_GH_AUTH_FILE=""

rehearsal_gh_auth_cleanup() {
    if [[ -n "$REHEARSAL_GH_AUTH_FILE" ]]; then
        rm -f -- "$REHEARSAL_GH_AUTH_FILE"
        REHEARSAL_GH_AUTH_FILE=""
    fi
}

# rehearsal_gh_auth_setup — create-or-refresh the header file; idempotent
# (reuses the existing file, so subshells inherit one shared path).
rehearsal_gh_auth_setup() {
    if [[ -z "$REHEARSAL_GH_AUTH_FILE" || ! -f "$REHEARSAL_GH_AUTH_FILE" ]]; then
        REHEARSAL_GH_AUTH_FILE=$(mktemp) || return 1
        chmod 600 "$REHEARSAL_GH_AUTH_FILE"
    fi
    printf 'Authorization: Bearer %s\n' "${LMER_REHEARSAL_GITHUB_TOKEN}" \
        > "$REHEARSAL_GH_AUTH_FILE"
}

# rehearsal_gh_api <METHOD> </path> [json-body]
rehearsal_gh_api() {
    local method="$1" path="$2" body="${3:-}"
    rehearsal_guard_credentials || return 1
    if [[ -z "${LMER_REHEARSAL_GITHUB_TOKEN:-}" ]]; then
        rehearsal_err "rehearsal_gh_api: LMER_REHEARSAL_GITHUB_TOKEN is not set"
        return 1
    fi
    rehearsal_gh_auth_setup || return 1
    local args=(
        -sS --fail
        -X "$method"
        -H "Accept: application/vnd.github+json"
        -H "@${REHEARSAL_GH_AUTH_FILE}"
        -H "X-GitHub-Api-Version: 2022-11-28"
    )
    if [[ -n "$body" ]]; then
        args+=(-H "Content-Type: application/json" -d "$body")
    fi
    curl "${args[@]}" "${REHEARSAL_GITHUB_API}${path}"
}

# rehearsal_json_get <dotted.path> — read JSON on stdin, print the value
# at the path ('' when absent). List indices are numeric path parts.
rehearsal_json_get() {
    python3 -c '
import json
import sys

obj = json.load(sys.stdin)
for part in sys.argv[1].split("."):
    if isinstance(obj, list):
        obj = obj[int(part)] if int(part) < len(obj) else None
    elif isinstance(obj, dict):
        obj = obj.get(part)
    else:
        obj = None
    if obj is None:
        break
print("" if obj is None else obj)
' "$1"
}

# rehearsal_json_string — JSON-encode stdin as a single string literal.
rehearsal_json_string() {
    python3 -c 'import json, sys; print(json.dumps(sys.stdin.read().rstrip("\n")))'
}

# rehearsal_find_run_for_tag <repo> <tag> — id of the newest release.yml
# run for the tag push ('' when none). Tag runs carry the tag name as
# head_branch.
rehearsal_find_run_for_tag() {
    local repo="$1" tag="$2"
    rehearsal_guard_repo "$repo" || return 1
    rehearsal_gh_api GET "/repos/${repo}/actions/runs?event=push&branch=${tag}" |
        python3 -c '
import json
import sys

wf_path = sys.argv[1]
for run in json.load(sys.stdin).get("workflow_runs", []):
    if run.get("path") == wf_path:
        print(run["id"])
        break
' "$REHEARSAL_WORKFLOW_PATH"
}

# rehearsal_poll_run <repo> <run-id> [timeout-s] [interval-s] — wait for
# an Actions run to complete; print its conclusion.
rehearsal_poll_run() {
    local repo="$1" run_id="$2" timeout="${3:-600}" interval="${4:-10}"
    rehearsal_guard_repo "$repo" || return 1
    local waited=0 body status
    while :; do
        body=$(rehearsal_gh_api GET "/repos/${repo}/actions/runs/${run_id}") || return 1
        status=$(printf '%s' "$body" | rehearsal_json_get status)
        if [[ "$status" == "completed" ]]; then
            printf '%s' "$body" | rehearsal_json_get conclusion
            return 0
        fi
        if (( waited >= timeout )); then
            rehearsal_err "rehearsal_poll_run: run ${run_id} still '${status}' after ${timeout}s"
            return 1
        fi
        sleep "$interval"
        waited=$(( waited + interval ))
    done
}

# rehearsal_rerun_run <repo> <run-id> [restart-timeout-s] [interval-s] —
# POST .../rerun, then wait until GitHub actually starts the new attempt
# (status leaves 'completed', or run_attempt increments past the pre-rerun
# value). Immediately after the POST the API can still serve the PREVIOUS
# attempt's completed status/conclusion; polling without this wait returns
# a stale conclusion (and acting on it can 403 a second rerun POST against
# a now-in-progress run).
rehearsal_rerun_run() {
    local repo="$1" run_id="$2" timeout="${3:-120}" interval="${4:-5}"
    rehearsal_guard_repo "$repo" || return 1
    local body prev_attempt status attempt waited=0
    body=$(rehearsal_gh_api GET "/repos/${repo}/actions/runs/${run_id}") || return 1
    prev_attempt=$(printf '%s' "$body" | rehearsal_json_get run_attempt)
    prev_attempt=${prev_attempt:-1}
    rehearsal_gh_api POST "/repos/${repo}/actions/runs/${run_id}/rerun" >/dev/null || return 1
    while :; do
        body=$(rehearsal_gh_api GET "/repos/${repo}/actions/runs/${run_id}") || return 1
        status=$(printf '%s' "$body" | rehearsal_json_get status)
        attempt=$(printf '%s' "$body" | rehearsal_json_get run_attempt)
        if [[ "$status" != "completed" ]]; then
            return 0
        fi
        if [[ "$attempt" =~ ^[0-9]+$ ]] && (( attempt > prev_attempt )); then
            return 0
        fi
        if (( waited >= timeout )); then
            rehearsal_err "rehearsal_rerun_run: run ${run_id} still reports the pre-rerun attempt (${prev_attempt}, completed) after ${timeout}s"
            return 1
        fi
        sleep "$interval"
        waited=$(( waited + interval ))
    done
}

# rehearsal_rig_workflow_fetch <repo> — the rig repo's committed release
# workflow (contents API, base64-decoded), for the drift guard's diff
# against the freshly derived output (README: Workflow derivation).
rehearsal_rig_workflow_fetch() {
    local repo="$1"
    rehearsal_guard_repo "$repo" || return 1
    rehearsal_gh_api GET "/repos/${repo}/contents/${REHEARSAL_WORKFLOW_PATH}" |
        python3 -c '
import base64
import json
import sys

doc = json.load(sys.stdin)
sys.stdout.write(base64.b64decode(doc["content"]).decode())
'
}

# rehearsal_run_jobs <repo> <run-id> — one "name<TAB>conclusion" per job.
rehearsal_run_jobs() {
    local repo="$1" run_id="$2"
    rehearsal_guard_repo "$repo" || return 1
    rehearsal_gh_api GET "/repos/${repo}/actions/runs/${run_id}/jobs" |
        python3 -c '
import json
import sys

for job in json.load(sys.stdin).get("jobs", []):
    print(job["name"], job.get("conclusion") or job.get("status") or "", sep="\t")
'
}

# rehearsal_release_lookup <repo> <tag> — the GitHub release JSON for a
# tag (non-zero when absent).
rehearsal_release_lookup() {
    local repo="$1" tag="$2"
    rehearsal_guard_repo "$repo" || return 1
    rehearsal_gh_api GET "/repos/${repo}/releases/tags/${tag}"
}

# ---------------------------------------------------------------------------
# TestPyPI
# ---------------------------------------------------------------------------

# rehearsal_testpypi_files <project> <version> — filenames published on
# TestPyPI for a release (read-only JSON API, no token needed).
rehearsal_testpypi_files() {
    local project="$1" version="$2"
    rehearsal_guard_project "$project" || return 1
    rehearsal_guard_url "$REHEARSAL_TESTPYPI_URL" || return 1
    curl -sS --fail "${REHEARSAL_TESTPYPI_URL}/pypi/${project}/${version}/json" |
        python3 -c '
import json
import sys

for entry in json.load(sys.stdin).get("urls", []):
    print(entry["filename"])
'
}

# rehearsal_testpypi_project_exists <project> — 0 iff the project has at
# least one release visible on TestPyPI.
rehearsal_testpypi_project_exists() {
    local project="$1"
    rehearsal_guard_project "$project" || return 1
    rehearsal_guard_url "$REHEARSAL_TESTPYPI_URL" || return 1
    curl -sS --fail -o /dev/null "${REHEARSAL_TESTPYPI_URL}/pypi/${project}/json"
}

# ---------------------------------------------------------------------------
# Evidence — one markdown file per rehearsal run, prose header plus a
# single fenced yaml block (README: Evidence format).
# ---------------------------------------------------------------------------

# rehearsal_release_job_order — job names of the production release
# workflow in definition order. Parsed from the workflow so the evidence
# verifier's "failed_job precedes publish-pypi" check tracks reality;
# falls back to the known order when the file is absent.
rehearsal_release_job_order() {
    local wf="${REHEARSAL_ROOT}/${REHEARSAL_WORKFLOW_PATH}"
    if [[ -f "$wf" ]]; then
        awk '
            /^jobs:[[:space:]]*$/ { injobs = 1; next }
            injobs && /^[^[:space:]#]/ { injobs = 0 }
            injobs && /^  [A-Za-z0-9_-]+:[[:space:]]*$/ {
                name = $1
                sub(/:$/, "", name)
                print name
            }
        ' "$wf"
    else
        printf '%s\n' verify-tag-signature verify-version checks build \
            publish-pypi github-release
    fi
}

# rehearsal_evidence_write field=value ... — write an evidence file and
# print its path. Fields mirror the README yaml block; recorded_at and
# the filename timestamp are supplied here. failed_job is optional
# (negatives only). The writer is permissive; rehearsal_verify_evidence
# is the strict end.
rehearsal_evidence_write() {
    local scenario="" rig_repo="" rig_project="" tag="" tag_sha=""
    local workflow_run_id="" workflow_run_url="" expected_conclusion=""
    local recorded_conclusion="" failed_job="" published="" derive_check=""
    local kv
    for kv in "$@"; do
        case "$kv" in
            scenario=*)            scenario=${kv#*=} ;;
            rig_repo=*)            rig_repo=${kv#*=} ;;
            rig_project=*)         rig_project=${kv#*=} ;;
            tag=*)                 tag=${kv#*=} ;;
            tag_sha=*)             tag_sha=${kv#*=} ;;
            workflow_run_id=*)     workflow_run_id=${kv#*=} ;;
            workflow_run_url=*)    workflow_run_url=${kv#*=} ;;
            expected_conclusion=*) expected_conclusion=${kv#*=} ;;
            recorded_conclusion=*) recorded_conclusion=${kv#*=} ;;
            failed_job=*)          failed_job=${kv#*=} ;;
            published=*)           published=${kv#*=} ;;
            derive_check=*)        derive_check=${kv#*=} ;;
            *)
                rehearsal_err "rehearsal_evidence_write: unknown field '${kv%%=*}'"
                return 2
                ;;
        esac
    done
    if [[ -z "$scenario" ]]; then
        rehearsal_err "rehearsal_evidence_write: scenario= is required"
        return 2
    fi
    local recorded_at stamp dir file
    recorded_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    stamp=$(date -u +%Y%m%dT%H%M%SZ)
    dir=${REHEARSAL_EVIDENCE_DIR:-${REHEARSAL_ROOT}/docs/rehearsal}
    mkdir -p "$dir"
    file="${dir}/evidence-${stamp}-${scenario}.md"
    {
        printf '# Rehearsal evidence: %s\n\n' "$scenario"
        printf 'Recorded by the lmer release rehearsal rig (Ctl/rehearsal). Re-check\n'
        printf 'offline with `Ctl/rehearsal/lib.sh --verify-evidence <this file>`.\n\n'
        printf '```yaml\n'
        printf 'scenario: %s\n' "$scenario"
        printf 'rig_repo: %s\n' "$rig_repo"
        printf 'rig_project: %s\n' "$rig_project"
        printf 'tag: %s\n' "$tag"
        printf 'tag_sha: %s\n' "$tag_sha"
        printf 'workflow_run_id: %s\n' "$workflow_run_id"
        printf 'workflow_run_url: %s\n' "$workflow_run_url"
        printf 'expected_conclusion: %s\n' "$expected_conclusion"
        printf 'recorded_conclusion: %s\n' "$recorded_conclusion"
        if [[ -n "$failed_job" ]]; then
            printf 'failed_job: %s\n' "$failed_job"
        fi
        printf 'published: %s\n' "$published"
        printf 'recorded_at: %s\n' "$recorded_at"
        printf 'derive_check: %s\n' "$derive_check"
        printf '```\n'
    } > "$file"
    printf '%s\n' "$file"
}

# rehearsal_evidence_yaml <file> — the contents of the fenced yaml block.
rehearsal_evidence_yaml() {
    awk '
        /^```yaml[[:space:]]*$/ { inblock = 1; next }
        /^```[[:space:]]*$/     { inblock = 0 }
        inblock
    ' "$1"
}

# rehearsal_evidence_get <file> <key> — value for a key in the yaml
# block, trailing comment stripped ('' when absent).
rehearsal_evidence_get() {
    local file="$1" key="$2"
    rehearsal_evidence_yaml "$file" |
        sed -n "s/^${key}:[[:space:]]*//p" |
        head -n 1 |
        sed 's/[[:space:]][[:space:]]*#.*$//; s/[[:space:]]*$//'
}

# rehearsal_verify_evidence <file> — the offline re-check (no network),
# exactly the README's rules: required fields present and well-formed,
# recorded_conclusion matches expected_conclusion, negative scenarios
# name a pre-publish failed_job and record published: false, and
# derive_check is pass.
rehearsal_verify_evidence() {
    local file="${1:?evidence file required}"
    if [[ ! -f "$file" ]]; then
        rehearsal_err "verify-evidence: no such file: $file"
        return 1
    fi

    local errors=0

    local scenario
    scenario=$(rehearsal_evidence_get "$file" scenario)
    local known=0 s
    for s in $REHEARSAL_SCENARIOS; do
        if [[ "$scenario" == "$s" ]]; then
            known=1
        fi
    done
    if (( ! known )); then
        rehearsal_err "verify-evidence: unknown scenario '${scenario}' (expected one of: ${REHEARSAL_SCENARIOS})"
        errors=$(( errors + 1 ))
    fi

    local field value
    for field in scenario rig_repo rig_project tag tag_sha workflow_run_id \
                 workflow_run_url expected_conclusion recorded_conclusion \
                 published recorded_at derive_check; do
        value=$(rehearsal_evidence_get "$file" "$field")
        if [[ -z "$value" ]]; then
            rehearsal_err "verify-evidence: missing required field '${field}'"
            errors=$(( errors + 1 ))
        fi
    done

    local tag_sha recorded_at expected recorded published derive_check failed_job
    tag_sha=$(rehearsal_evidence_get "$file" tag_sha)
    recorded_at=$(rehearsal_evidence_get "$file" recorded_at)
    expected=$(rehearsal_evidence_get "$file" expected_conclusion)
    recorded=$(rehearsal_evidence_get "$file" recorded_conclusion)
    published=$(rehearsal_evidence_get "$file" published)
    derive_check=$(rehearsal_evidence_get "$file" derive_check)
    failed_job=$(rehearsal_evidence_get "$file" failed_job)

    if [[ -n "$tag_sha" && ! "$tag_sha" =~ ^[0-9a-f]{40}$ ]]; then
        rehearsal_err "verify-evidence: tag_sha '${tag_sha}' is not 40 lowercase hex"
        errors=$(( errors + 1 ))
    fi
    if [[ -n "$recorded_at" && ! "$recorded_at" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
        rehearsal_err "verify-evidence: recorded_at '${recorded_at}' is not UTC ISO-8601 (YYYY-MM-DDThh:mm:ssZ)"
        errors=$(( errors + 1 ))
    fi
    case "$expected" in
        success|failure|"") ;;
        *)
            rehearsal_err "verify-evidence: expected_conclusion '${expected}' is not success/failure"
            errors=$(( errors + 1 ))
            ;;
    esac
    if [[ "$recorded" != "$expected" ]]; then
        rehearsal_err "verify-evidence: recorded_conclusion '${recorded}' does not match expected_conclusion '${expected}'"
        errors=$(( errors + 1 ))
    fi
    case "$published" in
        true|false|"") ;;
        *)
            rehearsal_err "verify-evidence: published '${published}' is not true/false"
            errors=$(( errors + 1 ))
            ;;
    esac
    if [[ "$derive_check" != "pass" ]]; then
        rehearsal_err "verify-evidence: derive_check is '${derive_check}', must be 'pass'"
        errors=$(( errors + 1 ))
    fi

    if [[ "$scenario" == negative-* ]]; then
        if [[ "$expected" != "failure" ]]; then
            rehearsal_err "verify-evidence: negative scenario must expect failure (got '${expected}')"
            errors=$(( errors + 1 ))
        fi
        if [[ "$published" != "false" ]]; then
            rehearsal_err "verify-evidence: negative scenario must record published: false"
            errors=$(( errors + 1 ))
        fi
        if [[ -z "$failed_job" ]]; then
            rehearsal_err "verify-evidence: negative scenario must name a failed_job"
            errors=$(( errors + 1 ))
        else
            # The failed job must precede publish-pypi in the workflow's
            # job order — a failure after publish is not a negative result.
            local order_ok=0 job
            while IFS= read -r job; do
                if [[ "$job" == "$REHEARSAL_PUBLISH_JOB" ]]; then
                    break
                fi
                if [[ "$job" == "$failed_job" ]]; then
                    order_ok=1
                fi
            done < <(rehearsal_release_job_order)
            if (( ! order_ok )); then
                rehearsal_err "verify-evidence: failed_job '${failed_job}' does not precede ${REHEARSAL_PUBLISH_JOB} in the release workflow job order"
                errors=$(( errors + 1 ))
            fi
        fi
    elif [[ "$scenario" == "leg2-dry-run" ]]; then
        if [[ "$expected" != "success" ]]; then
            rehearsal_err "verify-evidence: leg2-dry-run must expect success (got '${expected}')"
            errors=$(( errors + 1 ))
        fi
    fi

    if (( errors )); then
        rehearsal_err "verify-evidence: FAIL — ${errors} problem(s) in $file"
        return 1
    fi
    echo "verify-evidence: OK — $file (scenario: ${scenario})"
    return 0
}

# ---------------------------------------------------------------------------
# Executable entry point: offline evidence re-check.
# ---------------------------------------------------------------------------

_rehearsal_lib_usage() {
    cat <<'EOF'
usage: lib.sh --verify-evidence <evidence-file>

Offline re-check of a rehearsal evidence file (docs/rehearsal/
evidence-*.md). No network calls. Exit 0 iff the evidence is well-formed
and internally consistent per Ctl/rehearsal/README.md.
EOF
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    set -euo pipefail
    case "${1:-}" in
        --verify-evidence)
            if [[ $# -ne 2 ]]; then
                _rehearsal_lib_usage >&2
                exit 2
            fi
            rehearsal_verify_evidence "$2"
            ;;
        -h|--help)
            _rehearsal_lib_usage
            ;;
        *)
            _rehearsal_lib_usage >&2
            exit 2
            ;;
    esac
fi
